language: node_js
before_install:
- phantomjs --version
- npm install -g grunt-cli grunt-init bower
- bower install
branches:
  only:
  - master
node_js:
- '0.10'
before_script:
- git config --global user.name "Zhang JiuKun"
- git config --global user.email "jiukunz@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/jiukunz/blogist.git"
script:
- grunt-init config
- npm test
after_success:
- node crawl
- grunt sitemap
- git remote add blogist $REPO_URL
- git checkout -B gh-pages
- git rm .travis.yml -f
- git add sitemap.xml index.html javascripts bower_components -f
- git add CNAME
- git add gist rss.xml -f
- git commit -am 'publi:ship:'
- git push blogist gh-pages -f -q
env:
  global:
    secure: AGBTn5+5zPWiPjAcihmEM/gutt+vzTXT15rRpxYODeqZGXZRjcDr7SzEpLBPaq9yPVcFUJrdxZu4ws3zMHPexauZVbqhxt44e0bmkHSvg2ghKChl4HqLLyw1fkv8AAHnQxpnf/JGwxlS31hBCGWqnpa9wQAhLb/lIc/Q0dXaZC8=
